version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    logging:
      driver: "json-file"
      options:
        max-size: "15m"
        max-file: "3"
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 1234
    ports:
      - "5672:5672"    # AMQP 연결 포트
      - "15672:15672"  # 관리 콘솔 포트
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq-logs:/var/log/rabbitmq
      - ./rabbitmq-etc:/var/etc/rabbitmq